version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      rada_network:
        ipv4_address: 192.168.70.2

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      rada_network:
        ipv4_address: 192.168.70.3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-photo
    environment:
      PMA_HOST: mysql-photo
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    networks:
      rada_network:
        ipv4_address: 192.168.70.4

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mysql-photo
    environment:
      MYSQL_ROOT_PASSWORD: adminrmuti
      MYSQL_DATABASE: photo_match
      MYSQL_USER: rmuti
      MYSQL_PASSWORD: rmuti
    ports:
      - "3309:3306"
    networks:
      rada_network:
        ipv4_address: 192.168.70.5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password


networks:
  rada_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.70.0/24

volumes:
  web_data:
  mysql_data:
